repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Same version as in your pyproject.toml
    hooks:
      - id: black
        language_version: python3
        args: [--config=./pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Same version as in your pyproject.toml
    hooks:
      - id: isort
        args: [--settings-path=./pyproject.toml]

  - repo: https://github.com/pycqa/pylint
    rev: v2.17.4  # Same version as in your pyproject.toml
    hooks:
      - id: pylint
        additional_dependencies: [
          "pytest",
          "pyyaml",
          "jsonschema",
          "typing-extensions",
          "fastapi",
          "uvicorn",
          "python-multipart",
          "httpx",
        ]
        args: [
          "--rcfile=.pylintrc",
          "--disable=C0111,C0103,C0303,W1201,W1202,C0301,W0212,W0511,W0703,C0330,C0326,C0305,W0621,W0613,R0903,R0913,R0914,R0912,R0915,R0902,R0801,W0201,C0121,C0412,R0801,R1705,W0102,R0201,W0622,C0413,R1720,C0415,R1732,W0707,R1725,W0719,W0718,W0404,W0105,R0205,W0221,W0237,W0611,W0612,W0614,W0401,W0614,W0107,W0603,W0602,W0604,W0601,W0702,W0706,W0711,W0710,W0715,W0716,W0150,W0125,W0124,W0123,W0122,W0120,W0109,W0108,W0106,W0101,W0104,W0199,W0199,W0199,W0199,W0199,W0199,W0199,W0199,W0199,W0199,W0199",
        ]
